Styling
SamuelTakyiBoateng/BookStore pull request #5
Opened 2023-10-06 09:27 UTC by SamuelTakyiBoateng

## BookStore (Styling)
- Added missing Jsx elements.
- Styled UI to conform to Zeplin design.

2023-10-06 19:03 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @SamuelTakyiBoateng , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- All linters checks are passing as expected. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-07 04:26 UTC, SamuelTakyiBoateng commented on src/index.css
> +  font-family: sans-serif;
Thank you so much.
Please, changes have been effected. Thanks again!

2023-10-07 04:26 UTC, SamuelTakyiBoateng commented on src/components/Form.jsx
> +      </div>
Thank you so much.
Please, changes have been effected. Thanks again!

2023-10-07 04:57 UTC, Shedrack-Sunday approved these changes
Hi @SamuelTakyiBoateng

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![image](https://github.com/krisbobo/blog-app/assets/50990925/76d09bb1-9dc7-46c0-be49-31f366afa4b8)


Highlights
- [x] Good project organisation ✔️
- [x] Nice use of React features ✔️  
- [x] Kudus on meeting the requirements  as suggested by the last reviwer ✔️

### Confirmed view:
![image](https://github.com/SamuelTakyiBoateng/BookStore/assets/50990925/5cdaa7f1-0472-40d3-9441-600ffd4719e2)

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-10-07 15:13 UTC, merged